version: '3.8'

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - backend-dev
    networks:
      - portfolio-network

  backend-dev:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    command: npm run dev
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge