version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - portfolio-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    networks:
      - portfolio-network

  # Optional: Add database service
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: portfolio
  #     POSTGRES_USER: portfolio_user
  #     POSTGRES_PASSWORD: portfolio_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - portfolio-network

networks:
  portfolio-network:
    driver: bridge

# volumes:
#   postgres_data: